### ISSUE TITLE
Missing information for CUB TTI data_dir2

### ISSUE THREAD

**Issue by JackFurby** [yewsiang/ConceptBottleneck#18]
Hello,

To reproduce the TTI experiment an input parameter for `data_dar2` is required and the commands provided have the value of `CUB`. Looking at the function this command calls I have assumed this is for the complete CUB dataset in the same format as the processed version of CUB. I cannot find details on this however and am receiving the error message `AssertionError: len(instance_attr_labels): 631546, len(b_attr_labels): 648928` which I am assuming is due to the mask list generated having the following following value: `[  1   4   6   7  10  14  15  20  21  23  25  29  30  35  36  38  40  44 45  50  51  53  54  56  57  59  63  64  69  70  72  75  80  84  90  91 93 101 104 106 110 111 116 117 119 126 131 132 134 145 149 151 153 157 158 163 164 168 172 173 178 179 181 182 183 187 188 193 194 196 202 203 208 209 211 212 213 218 220 221 235 236 238 239 240 242 243 244 249 253 254 259 260 262 268 274 277 283 289 292 293 294 298 299 304 305 308 310 311]`. Comparing this to the concept in processed cub it is missing the concepts `99, 125, 152, 198, 225 and 309` while gaining the concepts `104, 173 and 182`. 

The attributes of each entry in train.pkl is as follows:

```
id: image ID
img_path: path to image file
class_label: label of image classification
attribute_label: list of length 312 containing 1 if concept at index is present and 0 if not
attribute_certainty: list of length 312 containing value of concept certainty where the index is the concept number
```

Is the AssertionError being thrown due to the mask value (the assert is defined on line 27 of tti.py)? And is it possible to have a copy of train.pkl and test.pkl for data_dir2 provided to reproduce the results in the paper?

Edit: I have also generated train and test files with data_processing.py with a similar outcome

**Comment by thaonguyen19** [comment]
based on the assertion error message it seems like `b_attr_labels` has 112 attributes/ image (which is the right number after aggregrating attributes on class levels), while `instance_attr_labels` only has 109. To clarify `data_dir2` is the directory where CUB with class-level attribute values is saved and we named it something like `class_attr_data_10` as the default. Did you follow the data processing instructions (first section of README.md)? The full processed data could also be found [here](https://worksheets.codalab.org/bundles/0x5b9d528d2101418b87212db92fea6683).

**Comment by JackFurby** [comment]
Hello @thaonguyen19,

Thank you for your reply. I have now managed to get TTI working. The issue turned out to be the `N_ATTRIBUTES` value in `CUB/config.py`. By default this is 312 but needed to be 112 for the class level concepts version of CUB. 

I did not need to run `generate_new_data.py` in the end but I noticed this may not be functioning. The function `get_class_attributes_data` in this file is defined but does not seem to be used. It also is a bit unclear the command to run for data processing from the instructions.

**Comment by SheltonZhaoK** [comment]
Hello @JackFurby,

Thank you for your solution. I also had that issue, and now it works. BTW, after running tti on my joint0.01 model, I discovered that the accuracy is acturally decreasing as the increase of the concept groups. Do you have similar issue?
