### ISSUE TITLE
Model choice for CUB

### ISSUE THREAD

**Issue by ThomasNorr** [yewsiang/ConceptBottleneck#21]
Hello,

thanks for your interesting work. I was wondering why you chose InceptionV3 for the experiments on CUB rather than Resnet18/50 which seems to be more common in the literature? 

I am grateful for some help.
Greetings

**Comment by kohpangwei** [comment]
Hi! We had no particular reason -- I think we were just trying to match previous work which used InceptionV3.

**Comment by ThomasNorr** [comment]
Thanks for the answer. 
Do you by any chance have tried resnet50 and have some hyperparameters/results for them?
I am trying to compare my work to yours on the basis of resnet50 too, as a lot of the competitors have used that (and my method seems to be benefit from resnet).

**Comment by ThomasNorr** [comment]
Additionally, I think there is an error in CUB/scripts/experiment.sh:
For the third seed of the joint model with lambda=0.01 the scheduler step is 20 instead of 1000

**Comment by kohpangwei** [comment]
Oh, thank you for catching that error! I've fixed it. I'm sorry but we didn't try resnet50, so we don't have any hyperparameters or results for them.
