### ISSUE TITLE
Hyperparameters

### ISSUE THREAD

**Issue by ThomasNorr** [yewsiang/ConceptBottleneck#22]
Hello,

What are the final hyperparameters used for the joint CUB model? 
https://github.com/yewsiang/ConceptBottleneck/blob/master/CUB/scripts/experiments.sh contains different values per seed, with the step size not in the reported range of the paper.

Also:
Do you by any chance have tried resnet50 and have some hyperparameters/results for them?
I am trying to compare my work to yours on the basis of resnet50 too, as a lot of the competitors have used that (and my method seems to be benefit from resnet).

Best regards

**Comment by kohpangwei** [comment]
Hi! Does this CodaLab worksheet help? https://worksheets.codalab.org/worksheets/0x362911581fcd4e048ddfd84f47203fd2  

Our results are pulled from here, and it should have all of the commands used. As you pointed out, unfortunately we messed up the scheduler_step for one of the seeds, but hopefully that doesn't affect the results too much.

**Comment by ThomasNorr** [comment]
Okay, I see. 
Thank you
