### ISSUE TITLE
Traveling Birds Dataset

### ISSUE THREAD

**Issue by ThomasNorr** [yewsiang/ConceptBottleneck#27]
Hello,

did you use all images in the train and test folders for training and testing with the Traveling Birds dataset or did you only use those assigned to train/test by CUB200?

Greetings

**Comment by kohpangwei** [comment]
Hi! I believe we used everything that's in https://worksheets.codalab.org/bundles/0x518829de2aa440c79cd9d75ef6669f27.

**Comment by ThomasNorr** [comment]
Hmm, I tried the dataset with a vanilla resnet50 and end up around your numbers when I respect the CUB200 split and achieve >60% accuracy when using the full train and testset provided in the folders.

How certain are you about your split?

And off-topic: Are you aware of other work that uses this dataset? All the citations of the paper make it hard to filter for the dataset :)

**Comment by thaonguyen19** [comment]
Have you used the dataset processing instructions in https://github.com/yewsiang/ConceptBottleneck/tree/master/CUB? We randomly sample 20% of the train split of CUB200 to use for validation. The CUB_processed folder then contains the metadata for all train/ val/ test splits

**Comment by thaonguyen19** [comment]
For Traveling Birds dataset, we follow the same split as CUB200 (i.e. validation data is included). See this script for more details https://github.com/yewsiang/ConceptBottleneck/blob/master/CUB/scripts/experiments.sh#L95

**Comment by ThomasNorr** [comment]
Okay, I see.
That makes sense, thank you
