### ISSUE TITLE
Concept Labels

### ISSUE THREAD

**Issue by Dadatata-JZ** [yewsiang/ConceptBottleneck#3]
Hi @yewsiang, 
While I am trying to apply the method with other datasets, I feel difficult to find the ground truths of the concepts (blue wings etc. ) for CUB data in your implementation. Could you please indicate me how to get the concept labels? It will be good if you can point out the funcs or the variable names. I couldn't find it out with a key word search as "concept". I am not sure if attribute labels refer to the concepts. 

Thank you in advance

**Comment by thaonguyen19** [comment]
Yes, "concept" is the same as attribute in our code. Please refer to our README for the 3 steps in the data processing pipeline. More specifically, after parsing the information from the official CUB-200-2011 dataset (available for download online), your metadata pickle file should contain 'attribute_label' as a field. Then you can use this [function](https://github.com/yewsiang/ConceptBottleneck/blob/master/CUB/generate_new_data.py#L65) to aggregate on the class level, like what we did in our paper to reduce labelling noise. Hope that helps, let me know if you have any further question!
