### ISSUE TITLE
Dataset link is dead?

### ISSUE THREAD

**Issue by oshapio** [yewsiang/ConceptBottleneck#30]
Thanks for sharing the code of your work.

I've been trying to access the dataset from worksheets.codalab.org, but it seems to be down, at least at the time of posting this. I was wondering if it would be possible for you to provide an alternative link? It would help a lot!

**Comment by kohpangwei** [comment]
Hi! I'm sorry but CodaLab is down and we don't have the dataset hosted elsewhere. The CodaLab team is aware of this and are trying to fix it -- hopefully in the next day or so.

**Comment by oshapio** [comment]
Seems to be back online - thanks for the prompt reply!
